Repository stanford-centaur/PyPantograph, pull requests merged in 2025-01, with the labels that each got.

#58 fix: Non-ascii symbol in payload
  pantograph/search.py
  pantograph/server.py
Labels: bug

#52 feat: Asynchronous Server Implementation; fix: Erroneous Statements in MiniF2F
  pantograph/server.py
  pantograph/utils.py
Labels: enhancement

#63 build: Add GitHub testing
  .github/workflows/test.yaml
Labels: build

#64 fix: Regex library name
  pantograph/utils.py
Labels: bug

#62 asyncio/pexpect fixes, small improvements
  pantograph/server.py
  pantograph/utils.py
Labels: enhancement
